glances: Autospec creation for update from version 3.1.0 to version 3.1.3
Bengt Lüers (1):
      Ignore loop back file systems under Ubuntu

Christopher Hiller (1):
      add intersphinx inventory

Christopher Viel (1):
      Fix missing future in devel-arm Dockerfile

Dan Church (1):
      Fix missing file during install

Emilien Mottet (3):
      add authprovider for cassandra export
      update example conf for connect cassandra with username and password
      fix tablename cassandra export and variabilize the cassandra table-name

Floran Brutel (7):
      :bug: Fix use of isLinux in the web ui
      Better handling of refresh time in the web ui
      :bug: Fix username handling when is null
      Better display of per-cpu component with a lot of cpus
      :arrow_up: webui packages
      :bug: Fix issue in webui with empty docker stats
      Fix custom refresh time in the web UI

Ghazi Triki (1):
      Update cmds.rst

Joe Abbey (1):
      Improve error handling when docker restarts

MendelGusmao (1):
      Filter duplicate public IP addresses in IP plugin

Nicolas Hennion (81):
      On the orad of Glances 3.1.1
      Update docs and NEWS file
      Documentation is unclear how to get Docker information #1386 and also add a all target to the Pip install in order to install all dependencies
      500 Internal Server Error /api/3/network/interface_name #1401
      Revert Permission denied: '/etc/glances/glances.conf' #1403 because Snapbuild fail
      ReRevert Permission denied: '/etc/glances/glances.conf' #1403
      Add an unitest for issue #1401
      Fan speed and voltages section? #1398
      Fan speed always high CPU consuming on my laptop...
      Add Snap packager
      Issue #1514 already corrected by issue #1348. Nevertheless, this commit improve code quality off the network plugin
      Fixes a typo in command-line options docs #1425
      Add NEWS file for ElasticSearch: add date to index, unbreak object push (thanks to @genevera) # 1438
      First commit with basic function. The plugin is to large. The default bahavor should be bar. Sparkline should be activated uppon --sparklines tag
      Size is now ok
      Connection to MQTT server failed : getaddrinfo() argument 2 must be integer or string #1450
      Change NEWS file
      `l` keypress (hide alert log) not working after some time #1449
      Version to be tested. All feature are implemented. Documentation to be done.
      Update documentation for sparklines.
      Ctach CertificateError in outdated plugin
      Add Load Average (similar to Linux) on Windows #344
      PsUtil 5.6.1. Bring load on Windows OS
      Too less data using prometheus exporter #1462
      Too less data using prometheus exporter #1462 (update doc and NEWS file)
      Getting an error when running with prometheus exporter #1469
      Stack trace when starts Glances on CentOS #1470
      Update doc
      Update sparkline with current %
      Quicklook is broken #1474
      Quicklook is broken #1474 (for both Python 2 and 3)
      Regression. Curses interface issue with Python 3. #1475
      Improve string encodeing/deconding
      Correct an issue with Loag plugin on Windows OS
      Glances crash on startup with a KeyError:u'docker' #1477
      Add Future lib
      A simple hask to disable plugin if a an error occurs on load
      Correct an issue introduced in latest commit
      Remove debug message
      UnicodeEncodeError: 'ascii' codec can't encode character u'\u25cf' - Raspbian stretch #1483
      Allow comma separated commands in AMP
      Performance issue with large folder #1491
      Can't connect to influxdb with https enabled #1497
      Prometheus integration broken with latest prometheus_client #1397
      "sorted by ?" is displayed when setting the sort criterion to "USER" #1407
      IP plugin displays incorrect subnet mask #1417
      docker glances container shows container's own network traffic #1435
      Glances PsUtil ValueError on IoCounter with TASK kernel options #1440
      Add support to detect WSL
      Glances 3.1.1RC1
      Fan speed and voltages section? #1398
      Glances 3.1.1
      Read player 3.1.2
      Error with IP Plugin : object has no attribute #1528
      Glances Snap doesn't run on Orange Pi Zero running Ubuntu Core 16 #1517
      [Feature Request] Option in config to change character used to display percentage in Quicklook #1511
      Make CSV export append instead of replace #1525
      Correct error in SMART unitest
      Update docs
      Update quicklook plugin doc
      HDDTEMP config IP? #1508
      Cannot restart glances with --export influxdb after update to 3.1.1 #1530
      Refactor all the way config file is loaded (now by each plugin). Should solve issues #1508.
      Add debug message for init and update duration (grep duration in log file when debug mode is on)
      Glances version 3.1.2
      On the road of the next version. 3.1.3 or 3.2.0
      Glances fails without network interface #1535
      Quicklook plugin not working on Systemd #1537
      Add a new TCP connections status plugin #1526 RC1
      Add conntrack
      Add color to nf_conn-track'
      Update doc for new connections plugin
      Add screenshot for connections plugins
      Update docs
      Update docs
      Harden Connections plugin
      Add shortcut to show / hide TCP connections (k)
      Remove debug message
      Correct an issue when a plugin is disabled from the cconf file
      Add --enable-plugin options from the command line
      version 3.1.3

Paul Sinclair (1):
      :ambulance: Fix typo for protocol, fixes #1514

Tom Deckers (1):
      Allow use of configuration files when installed as snap.

genevera (5):
      add date to index, unbreak object push
      use dynamic templating for values, clean up fields some more
      remove extra time field
      make _id more precise
      switch back to timestamp el name, clean up verbiage

netbuddy (1):
      repair the problem that when running 'glances --stdout-csv amps',report KeyError of amp plugin.

sangoh.hong (5):
      Page down key bug fixed.
      server status count added.
      Server list sorting added.
      Sorting Condition check added.
      improved server list sorting.

sentriz (1):
      show sensors alias in web interface

林博仁 (1):
      snap: Fix broken --webserver due to missing network-bind plug

林博仁(Buo-ren Lin) (13):
      Fix locale error due to missing compiled data
      Use local source tree for glances part
      Switch to automatic git versioning for snap version
      ReReRevert Permission denied: '/etc/glances/glances.conf' #1403
      Implement custom snap version string generation
      Use new metadata extracting feature in snaps
      Pin release of the runtime dependencies in snap
      Minimize history fetch depth to cut down pull time
      snap: Add packaging-specific gitignore rules
      snap: Support canonical config paths, fixes #1403
      snap: Migrate to `core` base
      snap: Unify sequence indentation style
      snap: Incorporate selective-checkout to ensure a revision for stable channel is always available