glances: Autospec creation for update from version 2.11 to version 3.1.0
Alessio Sergi (17):
      Drop support for EOL Python 3.3
      gids is not available on Windows
      standards_attr -> standard_attrs
      Use PEP 440 compliant version scheme
      Implement rich comparisons rather than relying on __cmp__()
      Take advantage of rich comparisons for PyPy too
      Unconditionally use statistics module since we support Python 3.4+ now
      Drop support for psutil < 5.3.0
      's/P[Ss][Uu]til/psutil/g'
      RESTful
      Pypi -> PyPI
      requirements.txt: psutil 5.4.3
      Use Travis container-based infrastructure
      Drop upgrade of both pip and setuptools on Travis
      Enable pip cache in Travis CI
      Add AppVeyor testing for Python 3.6
      Add python_requires to setup.py

Alyssa Ross (2):
      Don't load public IP address if module disabled
      Update Homebrew installation instructions

Andrew Janke (1):
      README: note that docker works on Mac

Conor O'Callaghan (1):
      Update README.rst

Emilien Mottet (2):
      `pwd`.conf instead of ./glances.conf
      fix typo in comment

Erik Eriksson (2):
      Support for exporting data to a MQTT server
      Don't use 100% CPU in quiet mode

Evan Dandrea (1):
      Add missing mount-observe and system-observe interfaces.

Floran Brutel (13):
      WebUi now take account of --fahrenheit option
      Set Fahrenheit values to 1 decimal
      Build the WebUI
      Check refresh time, if value < 1 then use the default value
      Support web url monitoring in web ui
      Add threads number in the process list of the webui
      Rebuild assets after update
      Handle empty values in the webUI (see #1251)
      Fix rounding of alert pourcent in the web interface
      Fix bug in bytes filter with Safari
      :arrow_up: Update javascript vendors
      Clean README of the WebUI
      Use process name when cmd line is empty

Greg Dahlman (1):
      Use nvidia-ml-py3 for python3 compatibility

John Kirkham (1):
      Require `requests` on Windows

Jordan Moore (1):
      Fix Docker ARM build

Matthew Jacobi (1):
      update readme docker run command

MendelGusmao (1):
      Prevent data truncation when receiving data from hddtemp server

Nick Efford (1):
      Fixes a link rendering problem in load.rst

Nicolas Hart (1):
      fix sensors plugin not displayed in web UI

Nicolas Hennion (242):
      Let's start Glances 3.x
      Creation of the maintenance branche for Glances 2.x
      Client and Quiet mode don't work together (issue #1139)
      Udpate doc for release 2.11.1
      Udpate version for release 2.11.1
      Failed to connect to bus: No such file or directory #1156
      Support for Docker API < 2.0 is deprecated (docker plugins)
      Correct an issue if the docker lib is not installed
      glances_plugin.py has a problem with specific docker output #1160
      Docker module doesn't export details about stopped containers #1152
      Crash in the Wifi plugin on my Laptop #1151
      A way to have only REST API available and disable WEB GUI access #1149
      Update docs
      Add a light mode for the console UI #1165
      Update NEWS file
      Docstings of plugins are now PEP 257 compliant
      Refactor InfluxDB (API is now stable) #1166
      The minimum supported API version is now 1.21 (Engine version 1.9.0+)
      Update Grafana Dashboard
      nicolargo/glances:latest breaks docker plugin #1174
      unable to install with pip #1088
      Key error 'address' in the IP plugin #1176
      NameError: name 'mode' is not defined in case of interrupt shortly after starting the server mode #1175
      Crash on startup: KeyError: 'hz_actual_raw' on Raspbian 9.1 #1170
      Docker plugin WebUI is broken in the latest DEVELOP branch #1174
      Correct an issue on Docker Status
      Make the left side bar width dynamic in the Curse UI #1177 - First run
      Remove debug message
      Job done for plugins IRQ, RAID, Folders and Port
      Make the left side bar width dynamic in the Curse UI #1177
      Hide an log message in the Glances cloud plugins
      Report from master of the PR: Add missing mount-observe and system-observe interfaces #1179
      OS specific arguments should be documented and reported #1180
      Refactor Curses
      Implement Gzip compression on the server side. Test Ok with Curl but the Web UI did not work anymore...
      Add Fossa badge
      Add Gzip support to unitaries tests
      Works fine in Python 2 but Internal Server Error with Python 3...
      Added using locale settings to encode wifi ssid. Replace any unknown … #1186
      'ascii' codec can't encode character u'\U0001f4a9' in position 4: ordinal not in range(128) #1185
      Correct an issue if Docker exists but no container running
      KeyError: 'memory_info' on stats sum #1188
      Another try for issue#1185
      Change default max sizebar size
      Electron processes displayed wrong in process list #1192
      Electron processes displayed wrong in process list (second round) #1192
      Electron processes displayed wrong in process list (remove debug message) #1192
      Change PGP key
      Correct another issue for command line display
      Remove commant
      Electron/Atom processes displayed wrong in process list #1192
      Refactor of the standalone main loop to be sure that it take more or less refresh_time. Also add debug log to investigate some potential freeze during stats update or export
      Add a method to convert str to ascii in Python 3
      Force string in Python3 to ascii convertion
      Another encoding issue... With both Python 2 and Python 3 #1197
      Add dynamic fields in all sections of the configuration file #1204
      Make plugin disable CLI option dynamical #1173
      Add support for the --modules-list
      Export module is now dynamic. Update doc
      Make plugins disable and export CLI option dynamical #1173
      Remove graph export from Glances #1206
      Glances do not exit when eating 'q' #1207
      Unitaries tests are broken after merge of issue#1204 #1210
      Add a code of conduct for Glances project's participants #1211
      FreeBSD blackhole bug #1202
      Disable warning message but in debug mode
      Context switches bottleneck identification #1212
      Fan speed sensors disable message from warning to debug
      Add plugs to Glances snap
      Add mailmap file (https://stacktoheap.com/blog/2013/01/06/using-mailmap-to-fix-authors-list-in-git/)
      First rush for the issue #1105. Bug with Process IO when Glances starts
      Correct IO counter and max cpu/mem
      Correct IO counter and max cpu/mem
      Max value does not work
      Merge pull request issue #1217
      Workaround for KeyError: 'docker' (see mail Alessio Sergi)
      Correct Max CPU MEM display
      Remove debug message
      Nice Process Priority Configuration #1218
      update readme docker run command #1219
      ZeroDivisionError in IO Rate (ProcessList) #1220
      Correct an issue on MacOS and SunOS for diskIO
      Revert the issue #1105 and create an update_NEW() function
      Ok but miss some extended stats (see line 348)
      Rename docker folder to docker-files because import docker return always true...
      Rename docker folder to docker-files because import docker return always true...
      Fallback for PsUtil 2.0
      Reafactoring almost done. Had to remove tree view...
      Remove tree view
      Correct issue https://github.com/nicolargo/glances/issues/1105#issuecomment-361051196 on MacOS
      Display debug message if dep lib is not found #1224
      Correct warning message typo
      Correct filter error if command name/line is None
      Change the filter order name than cmdline
      Correct https://github.com/nicolargo/glances/issues/1105#issuecomment-363553788
      Correct an issue on TIME+ on MacOS
      Add a new output mode to stdout #1168
      Correct help message
      Avoid Glances to crash with a IOError if duration <= 0 in the stdout display module (see https://stackoverflow.com/questions/36226054/strange-ioerror-when-time-sleep-in-python)
      Revert "Migrate from gulp & bower to webpack & yarn"
      Add Ansible role
      Add NEWS file concerning #1239
      Correct Gzip compression issue on Python 3.5
      Gzip ==> Defalte
      Glances crashes when mountpoint with non ASCII characters esists #1201
      Update unitest from gzip to deflate
      Glances 3.0 RC1
      [Glances 3.0 RC1] Client/Server is broken #1244
      Add long (but unused) log format
      Ok but too high CPU consumption
      Some change on the look and feel but CPU consumption is high...
      Graph are generated when the 'g' key is pressed
      Add Pygal option in the configuration file
      Subsample data for graph generation
      Add auto generation refresh time function
      Glances 3.0.rc2 (with new graph generation export module
      Correct an subsampling issue on Python 3
      Correct issue on Python 3
      Catch error message in Docker plugin
      New Grafana Dashboard
      Grafana Dashboard is now fully dynamic
      Fixing horizontal scrolling #1248
      Add time zone to the current time #1249
      Stats updated during export (thread issue) #1250
      Use https URLs for checking external IP #1253
      Add labels support to Promotheus exporter #1255
      glances --browser crashed when more than 40 glances servers on screen 78x45 #1256
      Add threads number in the process list #1259 Done for Curses UI. Need to be done in WebUI
      Update docs
      OSX - Python 3 and empty percent and res #1251 - To be tested
      Correct an issue to split the command line path and arguments
      Remove debug code
      Change copyright year to 2018
      Optimize process display
      Try a patch for issue #1260
      Crashes when influxdb option set #1260
      Reduce the number of log message during InfluxDB export
      Overlap in Web UI when monitoring a machine with 16 cpu threads #1265
      AMP for kernel process is not working #1261
      Remove debug message
      Enhance PerCpu/Cpu switch
      Change test for GPU
      Add human readable sort message for processes
      Remove dirty work arround for issue #1192 because PsUtil issue #1179 is now solved on PSUtil 5.4.2 and higher
      Add secondary sort key for processes
      Remove error message if the server is not running
      Improve debug messages for AMP
      Correct duplicate process numeber for kernel processes in AMPS (issue #1261)
      Align left for thread and IOw in the WebIU
      Enhance code quality: Arguments number differs from overridden 'update' method
      Correct Probable insecure usage of temp file/directory #820
      Try to update WebUI lib. To be checked by @notFloran
      Force UTF-8 encoding for Web server response
      Solve some encoding issue
      Arch linux package (2.11.1-2) psutil (v5.4.1): RuntimeWarning: ignoring OSError #1203
      Arch linux package (2.11.1-2) psutil (v5.4.1): RuntimeWarning: ignoring OSError #1203
      Glances crash with extended process stats #1283
      Terminal window stuck at the last accessed *protected* server #1275
      Add a F.A.Q in the documentation. Add respond for encoding issue
      Pin zeroconf dependency on 0.19 to maintain python 2 compatibility #1293
      Improve documentation concerning disk IO
      Add documentation about deps
      Upgrade RestFul API to api/3
      Glances shows mdadm RAID0 as degraded when chunksize=128k and the array isn't degraded. #1299
      Correct issue with RAID0
      Rebuild docs for #1305
      Update AUTHOR page
      Reduce the left column max size and remove the RAID test file
      Add documentation about Curses on Microsoft Windows (see issue #1312)
      Never starts in a server on Google Cloud and FreeBSD #1292
      Ready for Glances 3.0
      Update screenshot
      On the road of the next release. 3.0.1 or 3.1 ???
      Update NEWS file with 3.1 section
      AMPs error if no output are provided by the system call #1314
      Resolve issue in init file
      Correct some coding style in the HDD smart plugin
      Add smart lib in dep
      Add smart lib in README file
      TypeError: '<' not supported between instances of 'float' and 'str' #1315
      Update NEWS file
      Sort docker stats #1276
      Correct lint error in MQTT exporter
      Rename Glances logs to Glances events
      Disable automatic sorting between cpu_percent, io_counters and memory_percent #1317
      Add history to GPU stats. Allowing user to export stats (see #1319)
      Add Docker container for ARM
      Correct issue on ARM Docker file
      Add Alpine based container
      Change the way cpu_times (per processes) is computed
      Glances IO Errorno 22 - Invalid argument #1326
      Glances IO Errorno 22 - Invalid argument #1326
      Glances 3.0.2 (Hotfix version)
      Change NEWS file followinf release of Glances 3.0.2
      Add link to repology web site
      Correct Pep issue on string
      GPU plugin not exported to influxdb #1333
      Crash after running fine for several hours #1335
      Timezone listed doesn’t match system timezone, outputs wrong time #1337
      Update NEWS file
      Add Docker doc to the index
      remove duplicate JSON in help page
      error type host : AWS EC2 on VM public OVH ;( #1340
      KeyError: 'eth0' when interface is not connected #1348
      Compare issue with Process.cpu_times() #1339
      Configure Python 3.6 in Tox
      ERROR -- Can not grab extended stats (invalid attr name 'num_fds') #1351
      Add CPU profiling page
      Replace the wait method by a default timeout on getch
      Recompute refresh after a key pressed
      Ok for Web and Port
      Correct folders alert
      Support for monochrome (serial) terminals e.g. vt220 #1362
      Implementation of the CSV format for the STDOUT plugin done. Had to update the documentation
      Add a CSV output format to the STDOUT output mode #1363
      Update documentation
      Add some comments
      Some field name are incorrect in CSV export #1372 and Prohibit some plug-in data from being exported to influxdb #1368
      TypeError on opening (Wifi plugin) #1373
      Correct NoneType issue on Wifi signal (related to issue #1973)
      Standard output misbehaviour (need to flush) #1376
      Update documentation
      Disable Wifi plugin for Python 3
      Disable plugin from Glances configuration file #1378
      Add a simple Makefile
      Update installation documentation for Mac OS X
      Create an option to set the username to use in Web or RPC Server mode #1381
      Correct an issue with unitest on Python 3.x
      Add download/month badge
      Missing kernel task names when the webui is switched to long process names #1371
      Drive name with special characters causes crash #1383
      Drive name with special characters causes crash (correct) #1383
      Update README
      Update README.rst
      Update README.rst
      Update README.rst
      Update README.rst
      Remove Circle.yml
      Update NEWS file with latest PR
      Cannot get stats in Cloud plugin (404) #1384
      'chart' extra not provided #1389
      Glances 3.1.0

Rémy G (1):
      Create docker.rst

Sebastien Badia (1):
      docs: man - Fix spelling typo (separed → separated)

Steven Conaway (1):
      Update fs.rst

Tieu-Philippe KHIM (63):
      fix on macOS when value is NoneType when compute the max values
      remove bower and use webpack
      adding webpack.config.js
      remove normalize because bootstrap provide it
      update components for webpack
      update services
      update root js
      update template to use glances.js file, and remove older bower stuff
      adding package-lock.json
      ignoring public folder
      add missing export default on favicon
      remove gulp stuff
      adding scss and less loaders
      remove static bootstrap.css
      move style.css to style.scss
      adding bootstrap less files & variables
      update quicklook-plugin with nested class
      keep only needed modules on bootstrap
      adding webpack configuration to support less
      import bootstrap configuration on app
      add package-lock.json in case of using npm
      update readme.md to add yarn in build instruction
      adding import angular, remove use strict and update simple quote to double quote
      on webpack.config replace simple quote by double quote and remove angular plugin
      adding clean webpack plugin to cleanup public folder on build
      remove public/favicon.ico, webpack handle the copy from image
      replace simple quote by double quote
      convert functions filter name to camelcase
      on favicon.js, move the export default to the end and update simple quote to double quote
      remove bower and use webpack
      adding webpack.config.js
      remove normalize because bootstrap provide it
      update components for webpack
      update services
      update root js
      update template to use glances.js file, and remove older bower stuff
      adding package-lock.json
      ignoring public folder
      add missing export default on favicon
      remove gulp stuff
      adding scss and less loaders
      remove static bootstrap.css
      move style.css to style.scss
      adding bootstrap less files & variables
      update quicklook-plugin with nested class
      keep only needed modules on bootstrap
      adding webpack configuration to support less
      import bootstrap configuration on app
      add package-lock.json in case of using npm
      update readme.md to add yarn in build instruction
      adding import angular, remove use strict and update simple quote to double quote
      on webpack.config replace simple quote by double quote and remove angular plugin
      adding clean webpack plugin to cleanup public folder on build
      remove public/favicon.ico, webpack handle the copy from image
      replace simple quote by double quote
      convert functions filter name to camelcase
      on favicon.js, move the export default to the end and update simple quote to double quote
      remove .gitignore on glances/output/static
      cleanup public folder
      on webpack adding favicon.ico file to copy to public folder
      add public folder with generated assets
      remove public subfolder in public
      adding missing directives.js

Tim Nibert (3):
      Hard disk SMART plugin, includes python3 patched pySMART
      Removed pySMART version hack, now using pySMART.smartx from pip
      fixed test for appveyor

Tomáš Vyčítal (5):
      Implement number and alias aware diskio sorting
      Move alias aware sorting to glances_plugin
      Use alias aware sorting in glances_network
      Use get_key instead of hardcoded names in sorted_stats
      Add a unit test for plugin's sorted stats method

Webysther Nunes (1):
      Add link to config

cheezeburger (1):
      Added alternative Python installation method

sangoh.hong (4):
      curses-browser's server list paging added.
      Client Browser's thread management added.
      added web['ssl_verify'] & web['proxies']
      modify  proxies argument.