glances: Autospec creation for update from version 3.2.3.1 to version 3.2.5
Floran Brutel (3):
      Upgrade Webpack to v4
      Update to webpack 5
      Use npm ci instead of npm install

H4ckerxx44 (3):
      missing d in function name:
      missing d in function name:
      small oversights

Hugo van Kemenade (2):
      Add support for Python 3.10
      Replace Travis CI badge with GitHub Action

Karthikeyan Singaravelan (1):
      Use is_set instead of isSet for Python 3.10 compatibility.

Mohamad Mansour (1):
      fixed typo

Moldavite (1):
      Added missing options to help menu

Nicolas Hennion (55):
      Back on the road of the version 3.2.4
      Separate battery percentages #1920
      Update documentation
      distutils is deprecated in Python 3.10 #1923
      Refactor CPU Curses code
      Refactor Mem + MemSwap Curse
      Correct an issue on idle display
      Influxdb2 via SSL #1934
      Failure to start on Apple M1 Max #1939
      Update UI
      Swith from black <> white theme with the '9' hotkey - Related to issue #976
      Update docs and correct make docs-server target in Makefile
      Improve --issue option with Python version and paths
      Improve --issue by displaying the second update iteration and not the first one. More relevant
      Glances 3.2.4
      On the road of Glances v3.2.5
      On the road of Glances v3.2.5 again
      Glances 3.2.4.1
      On the road again again
      KeyError: 'syscalls' and terminal layout broken with Glances 3.2.4+ #1956
      Glances 3.2.4.2
      Update docs
      Grafana dashboards not displayed with influxdb2 #1960
      Update InfluxDB documentation
      Load plugin - OSError: [WinError 87] on Windows 10 #1965
      Reduce CPU in server mode by disabling the processes extended stats
      glances_ip.py plugin relies on low rating / malicious site domain #1975
      --time parameter being ignored for client/server mode #1978
      Random numbers in Client mode #1979
      Web server status check endpoint #1988
      Update docs for API. Related to issue #1988
      Update docs (again) for API. Related to issue #1988
      Including battery and AC adapter health in Glances #1049
      Update profiling flame file
      Add line separators in the terminal output #1996
      The gpu temperature unit are displayed incorrectly in web ui #2002
      Add a trace malloc test
      Add --memory-leak option
      Disable history when --memory-leak option is used
      Add memory leak target in makefile
      Prepare memory leak test. Not active for the moment
      Correct issue on run
      Add uptime to the Docher plugin - #2004
      Correct unitary test issue in Python 2
      First running version. Need more test. And WebUI
      Correct typo in documentation
      Update WebUI and docs
      Kill is now compatible with Programs
      Correct an issue with the kill function
      Format code thanks to Black
      Clear-text logging of sensitive information
      Amp with pipe do not work #1976
      Glances reports different amounts of used memory than free -m or top #1924
      Update release note for Glances 3.2.5
      Update release note for Glances 3.2.5

Néfix Estrada (1):
      Fix Grafana CPU temperature panel

RazCrimson (22):
      Fix: Docker plugin - Network stats typo bug
      Docker plugin - Fix typos in comments
      Docker plugin - Remove unused imports
      Docker plugin - Minor changes and cleanup
      Fix: Docker plugin - Invalid IO stats with Arch Linux
      refactor: Docker Plugin - Reduce computation for network and io stats
      refactor: Docker Plugin - Reorder imports
      refactor: Docker Plugin - Rename variables & Reformat code
      refactor: Docker Plugin - Remove legacy comments
      refactor: AMPs cleanup
      refactor: Exports cleanup
      refactor: Outputs cleanup
      refactor - Plugins cleanup
      refactor - Core cleanup
      refactor - Minor typo fixes in cleanup
      add: black in dev-requirements.txt
      add: pyproject.toml for black config
      add: Makefile entries for black formatting & testing
      refactor: Reformat existing code to comply with black
      fix: Command trimmed incorrectly #1795
      fix: autodiscover.py failure
      fix: Typo in docs

Zameer Manji (1):
      Update debian image to include `smartmontools`

ledwards (1):
      Updated FreeBSD installation instructions

myersg86 (1):
      Fix typo in CONTRIBUTING.md